# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reduceChromatinAccessibility <- function(expression, reduced_dim = 30L, method = 1L, iters = 10L) {
    .Call(`_ATACtion_reduceChromatinAccessibility`, expression, reduced_dim, method, iters)
}

